#ifndef TACC_PREDEF_FUNC_H
#define TACC_PREDEF_FUNC_H

enum tacc_predef_func_id {
    PREDEF__TACCRT_FIXTFDI,
    PREDEF__TACCRT_FIXUNSTFDI,
    PREDEF__TACCRT_FLOATDITF,
    PREDEF__TACCRT_FLOATUNSDITF,
    PREDEF__TACCRT_FIXTFSI,
    PREDEF__TACCRT_TRUNCTFSF2,
    PREDEF__TACCRT_TRUNCTFDF2,
    PREDEF__TACCRT_EXTENDSFTF2,
    PREDEF__TACCRT_EXTENDDFTF2,
};

#endif
